spring.application.name=crosswords
opensearch.uris=${OPENSEARCH_URIS}
opensearch.username=${OPENSEARCH_USERNAME}
opensearch.password=${OPENSEARCH_PASSWORD}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.database=postgresql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL}
server.port=8081
jwt_secret=${JWT_SECRET}
jwt_accessExpirationDate=15
jwt_refreshExpirationDate=10080
scheduler.cron=0 0 6 * * *
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
server.servlet.encoding.force-response=true
mailman.url=http://mailman:5001
mailman.send-email-path=/send-email
mailman.verify-email-path=/verify_email
mailman.connect-timeout=5000
mailman.response-timeout=10000
digest-generator.url=http://digest-service:5000
digest-generator.generate-digest-path=/
digest-generator.connect-timeout=5000
digest-generator.response-timeout=30000
backend-secret-key=${BACKEND_SECRET_KEY}
default-admins-password=${DEFAULT_ADMINS_PASSWORD}
springdoc.api-docs.enabled=${CREATE_SWAGGER}
springdoc.swagger-ui.enabled=${CREATE_SWAGGER}
springdoc.show-actuator=${CREATE_SWAGGER}
crosswords-firebase-credentials = ${CROSSWORDS_FIREBASE_CREDENTIALS}
crosswords-firebase-projectid = ${CROSSWORDS_FIREBASE_PROJECTID}
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true
spring.flyway.encoding=UTF-8
# Telegram Bot
telegram.bot.url=https://crosswords-tgbot.jujacloud.tech
telegram.bot.internal-secret=${TELEGRAM_BOT_INTERNAL_SECRET}
